<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Content;

class ContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $contents = [
            // HOME PAGE CONTENT
            [
                'page_slug' => 'home',
                'key' => 'about_section_title',
                'value' => 'About Us',
                'type' => 'text',
                'group' => 'about_section',
                'description' => 'About section main title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'home',
                'key' => 'about_section_subtitle',
                'value' => 'Connecting international patients with world-class healthcare in India',
                'type' => 'text',
                'group' => 'about_section',
                'description' => 'About section subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'home',
                'key' => 'mission_title',
                'value' => 'Our Mission',
                'type' => 'text',
                'group' => 'about_section',
                'description' => 'Mission card title',
                'display_order' => 3,
            ],
            [
                'page_slug' => 'home',
                'key' => 'mission_text',
                'value' => 'To connect international patients with trusted hospitals, renowned doctors, and affordable world-class treatments in India, ensuring a seamless and compassionate medical journey.',
                'type' => 'textarea',
                'group' => 'about_section',
                'description' => 'Mission description',
                'display_order' => 4,
            ],
            [
                'page_slug' => 'home',
                'key' => 'vision_title',
                'value' => 'Our Vision',
                'type' => 'text',
                'group' => 'about_section',
                'description' => 'Vision card title',
                'display_order' => 5,
            ],
            [
                'page_slug' => 'home',
                'key' => 'vision_text',
                'value' => 'To become a globally recognized medical tourism facilitator known for ethical practices, patient-centric care, and long-term international healthcare partnerships.',
                'type' => 'textarea',
                'group' => 'about_section',
                'description' => 'Vision description',
                'display_order' => 6,
            ],
            [
                'page_slug' => 'home',
                'key' => 'about_additional_text',
                'value' => 'At Fight From Diseases, we are committed to making world-class healthcare accessible to patients from around the globe. Our dedicated team works tirelessly to ensure every patient receives personalized care, transparent communication, and the best possible medical outcomes.',
                'type' => 'textarea',
                'group' => 'about_section',
                'description' => 'Additional about text',
                'display_order' => 7,
            ],
            [
                'page_slug' => 'home',
                'key' => 'hospitals_section_title',
                'value' => 'Our Partner Hospitals',
                'type' => 'text',
                'group' => 'hospitals_section',
                'description' => 'Partner hospitals section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'home',
                'key' => 'hospitals_section_subtitle',
                'value' => 'Trusted multi-speciality and super-speciality hospitals across India',
                'type' => 'text',
                'group' => 'hospitals_section',
                'description' => 'Partner hospitals section subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'home',
                'key' => 'specialities_section_title',
                'value' => 'Medical Specialities',
                'type' => 'text',
                'group' => 'specialities_section',
                'description' => 'Specialities section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'home',
                'key' => 'specialities_section_subtitle',
                'value' => 'Comprehensive healthcare services across multiple specialities',
                'type' => 'text',
                'group' => 'specialities_section',
                'description' => 'Specialities section subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'home',
                'key' => 'gallery_section_title',
                'value' => 'Photo Gallery',
                'type' => 'text',
                'group' => 'gallery_section',
                'description' => 'Photo gallery section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'home',
                'key' => 'gallery_section_subtitle',
                'value' => 'Explore our world-class facilities and patient care environments',
                'type' => 'text',
                'group' => 'gallery_section',
                'description' => 'Photo gallery section subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'home',
                'key' => 'cta_section_title',
                'value' => 'Ready to Start Your Medical Journey?',
                'type' => 'text',
                'group' => 'cta_section',
                'description' => 'CTA section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'home',
                'key' => 'cta_section_description',
                'value' => 'Get in touch with us today and let us help you find the best medical treatment in India.',
                'type' => 'textarea',
                'group' => 'cta_section',
                'description' => 'CTA section description',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'home',
                'key' => 'cta_button_text',
                'value' => 'Contact Us Now',
                'type' => 'text',
                'group' => 'cta_section',
                'description' => 'CTA button text',
                'display_order' => 3,
            ],

            // ABOUT PAGE CONTENT
            [
                'page_slug' => 'about',
                'key' => 'hero_title',
                'value' => 'About Fight From Diseases',
                'type' => 'text',
                'group' => 'hero',
                'description' => 'About page hero title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'about',
                'key' => 'hero_subtitle',
                'value' => 'We are passionate about connecting people from around the world with exceptional healthcare opportunities in India, making quality medical treatment accessible and affordable for everyone.',
                'type' => 'textarea',
                'group' => 'hero',
                'description' => 'About page hero subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'about',
                'key' => 'mission_title',
                'value' => 'Our Mission',
                'type' => 'text',
                'group' => 'mission',
                'description' => 'Mission section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'about',
                'key' => 'mission_text',
                'value' => 'To connect international patients with trusted hospitals, renowned doctors, and affordable world-class treatments in India, ensuring a seamless and compassionate medical journey.',
                'type' => 'textarea',
                'group' => 'mission',
                'description' => 'Mission description',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'about',
                'key' => 'vision_title',
                'value' => 'Our Vision',
                'type' => 'text',
                'group' => 'vision',
                'description' => 'Vision section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'about',
                'key' => 'vision_text',
                'value' => 'To become a globally recognized medical tourism facilitator known for ethical practices, patient-centric care, and long-term international healthcare partnerships.',
                'type' => 'textarea',
                'group' => 'vision',
                'description' => 'Vision description',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'about',
                'key' => 'values_section_title',
                'value' => 'Our Core Values',
                'type' => 'text',
                'group' => 'values',
                'description' => 'Values section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'about',
                'key' => 'values_section_subtitle',
                'value' => 'The principles that guide everything we do',
                'type' => 'text',
                'group' => 'values',
                'description' => 'Values section subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'about',
                'key' => 'value_trust_title',
                'value' => 'Trust & Reliability',
                'type' => 'text',
                'group' => 'values',
                'description' => 'Trust value title',
                'display_order' => 3,
            ],
            [
                'page_slug' => 'about',
                'key' => 'value_trust_text',
                'value' => 'At Fight From Diseases, we build trust through transparency, honest communication, and partnerships with only the most reputable healthcare institutions. Every recommendation we make is backed by thorough research and genuine care for your wellbeing.',
                'type' => 'textarea',
                'group' => 'values',
                'description' => 'Trust value description',
                'display_order' => 4,
            ],
            [
                'page_slug' => 'about',
                'key' => 'value_community_title',
                'value' => 'Community First',
                'type' => 'text',
                'group' => 'values',
                'description' => 'Community value title',
                'display_order' => 5,
            ],
            [
                'page_slug' => 'about',
                'key' => 'value_community_text',
                'value' => 'Your health journey is our shared mission. We foster a supportive community where patients, families, and healthcare providers work together to achieve positive outcomes and lasting wellness.',
                'type' => 'textarea',
                'group' => 'values',
                'description' => 'Community value description',
                'display_order' => 6,
            ],
            [
                'page_slug' => 'about',
                'key' => 'value_innovation_title',
                'value' => 'Innovation',
                'type' => 'text',
                'group' => 'values',
                'description' => 'Innovation value title',
                'display_order' => 7,
            ],
            [
                'page_slug' => 'about',
                'key' => 'value_innovation_text',
                'value' => 'We stay at the forefront of medical tourism by embracing new technologies, advanced treatment methods, and innovative care approaches that deliver better results for our patients.',
                'type' => 'textarea',
                'group' => 'values',
                'description' => 'Innovation value description',
                'display_order' => 8,
            ],
            [
                'page_slug' => 'about',
                'key' => 'what_we_do_title',
                'value' => 'What We Do',
                'type' => 'text',
                'group' => 'what_we_do',
                'description' => 'What we do section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'about',
                'key' => 'what_we_do_subtitle',
                'value' => 'How we support your medical journey from start to finish',
                'type' => 'text',
                'group' => 'what_we_do',
                'description' => 'What we do section subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'about',
                'key' => 'cta_title',
                'value' => 'Join Us in Making a Difference',
                'type' => 'text',
                'group' => 'cta',
                'description' => 'CTA section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'about',
                'key' => 'cta_description',
                'value' => 'Together, we can create a healthier future. Get involved and be part of the change.',
                'type' => 'textarea',
                'group' => 'cta',
                'description' => 'CTA section description',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'about',
                'key' => 'cta_button_text',
                'value' => 'Contact Us Today',
                'type' => 'text',
                'group' => 'cta',
                'description' => 'CTA button text',
                'display_order' => 3,
            ],

            // CONTACT PAGE CONTENT
            [
                'page_slug' => 'contact',
                'key' => 'hero_title',
                'value' => 'Get in Touch',
                'type' => 'text',
                'group' => 'hero',
                'description' => 'Contact page hero title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'contact',
                'key' => 'hero_subtitle',
                'value' => 'We\'re here to answer your questions and guide you through every step of your medical journey. Get in touch with our team today.',
                'type' => 'textarea',
                'group' => 'hero',
                'description' => 'Contact page hero subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'contact',
                'key' => 'form_title',
                'value' => 'Send Us a Message',
                'type' => 'text',
                'group' => 'form',
                'description' => 'Contact form section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'contact',
                'key' => 'form_description',
                'value' => 'Fill out the form below and we\'ll get back to you as soon as possible.',
                'type' => 'textarea',
                'group' => 'form',
                'description' => 'Contact form description',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'contact',
                'key' => 'contact_info_title',
                'value' => 'Contact Information',
                'type' => 'text',
                'group' => 'contact_info',
                'description' => 'Contact information section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'contact',
                'key' => 'map_section_title',
                'value' => 'Find Us',
                'type' => 'text',
                'group' => 'map',
                'description' => 'Map section title',
                'display_order' => 1,
            ],

            // HEALTH RESOURCES PAGE
            [
                'page_slug' => 'health-resources',
                'key' => 'hero_title',
                'value' => 'Health Resources',
                'type' => 'text',
                'group' => 'hero',
                'description' => 'Health resources page hero title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'hero_subtitle',
                'value' => 'Access valuable health information, helpful tools, and essential resources designed to support you throughout your healthcare journey in India.',
                'type' => 'textarea',
                'group' => 'hero',
                'description' => 'Health resources page hero subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'resource_medical_guides_title',
                'value' => 'Medical Guides',
                'type' => 'text',
                'group' => 'resources',
                'description' => 'Medical guides card title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'resource_medical_guides_text',
                'value' => 'Access detailed, easy-to-understand guides covering a wide range of medical conditions, treatment options, and procedures. These resources are designed to help you make informed decisions about your healthcare journey.',
                'type' => 'textarea',
                'group' => 'resources',
                'description' => 'Medical guides card description',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'resource_treatment_info_title',
                'value' => 'Treatment Information',
                'type' => 'text',
                'group' => 'resources',
                'description' => 'Treatment information card title',
                'display_order' => 3,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'resource_treatment_info_text',
                'value' => 'Explore comprehensive information about advanced medical treatments, surgical procedures, and therapeutic options available at our partner hospitals in India. Learn about what to expect before, during, and after your treatment.',
                'type' => 'textarea',
                'group' => 'resources',
                'description' => 'Treatment information card description',
                'display_order' => 4,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'resource_hospital_directory_title',
                'value' => 'Hospital Directory',
                'type' => 'text',
                'group' => 'resources',
                'description' => 'Hospital directory card title',
                'display_order' => 5,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'resource_hospital_directory_text',
                'value' => 'Browse our carefully curated directory of partner hospitals across India. Each listing includes detailed information about facilities, medical specialities, accreditations, and the range of services offered.',
                'type' => 'textarea',
                'group' => 'resources',
                'description' => 'Hospital directory card description',
                'display_order' => 6,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'resource_cost_calculator_title',
                'value' => 'Cost Calculator',
                'type' => 'text',
                'group' => 'resources',
                'description' => 'Cost calculator card title',
                'display_order' => 7,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'resource_cost_calculator_text',
                'value' => 'Use our cost estimation tool to get approximate pricing for various medical procedures and treatments. Compare costs across different partner hospitals to help you plan your medical journey effectively.',
                'type' => 'textarea',
                'group' => 'resources',
                'description' => 'Cost calculator card description',
                'display_order' => 8,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'resource_travel_guide_title',
                'value' => 'Travel Guide',
                'type' => 'text',
                'group' => 'resources',
                'description' => 'Travel guide card title',
                'display_order' => 9,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'resource_travel_guide_text',
                'value' => 'Navigate your journey to India with confidence using our comprehensive travel guide. Find essential information about visa requirements, travel arrangements, accommodation options, and local insights for medical tourists.',
                'type' => 'textarea',
                'group' => 'resources',
                'description' => 'Travel guide card description',
                'display_order' => 10,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'resource_appointment_booking_title',
                'value' => 'Appointment Booking',
                'type' => 'text',
                'group' => 'resources',
                'description' => 'Appointment booking card title',
                'display_order' => 11,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'resource_appointment_booking_text',
                'value' => 'Book consultations with leading medical specialists and renowned hospitals through our streamlined appointment system. We handle all the coordination to make scheduling as simple as possible for you.',
                'type' => 'textarea',
                'group' => 'resources',
                'description' => 'Appointment booking card description',
                'display_order' => 12,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'cta_title',
                'value' => 'Need More Information?',
                'type' => 'text',
                'group' => 'cta',
                'description' => 'CTA section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'cta_description',
                'value' => 'Our team is here to help you access the health resources you need.',
                'type' => 'textarea',
                'group' => 'cta',
                'description' => 'CTA section description',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'health-resources',
                'key' => 'cta_button_text',
                'value' => 'Contact Us',
                'type' => 'text',
                'group' => 'cta',
                'description' => 'CTA button text',
                'display_order' => 3,
            ],

            // HEALTH TIPS PAGE
            [
                'page_slug' => 'health-tips',
                'key' => 'hero_title',
                'value' => 'Health Tips',
                'type' => 'text',
                'group' => 'hero',
                'description' => 'Health tips page hero title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'hero_subtitle',
                'value' => 'Discover practical, actionable tips and advice to help you maintain your health and wellness, whether you\'re preparing for treatment or focusing on prevention.',
                'type' => 'textarea',
                'group' => 'hero',
                'description' => 'Health tips page hero subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'tip_hydration_title',
                'value' => 'Stay Hydrated',
                'type' => 'text',
                'group' => 'tips',
                'description' => 'Hydration tip title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'tip_hydration_text',
                'value' => 'Maintaining proper hydration is essential for your body to function optimally. Aim for 8-10 glasses of water daily, and remember that fruits and vegetables also contribute to your hydration needs. Keep a reusable water bottle nearby as a helpful reminder to drink regularly throughout your day.',
                'type' => 'textarea',
                'group' => 'tips',
                'description' => 'Hydration tip description',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'tip_diet_title',
                'value' => 'Eat a Balanced Diet',
                'type' => 'text',
                'group' => 'tips',
                'description' => 'Diet tip title',
                'display_order' => 3,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'tip_diet_text',
                'value' => 'Nourish your body with a colorful variety of fresh fruits and vegetables, whole grains, and quality protein sources. While occasional treats are fine, try to minimize highly processed foods, added sugars, and excessive sodium. This balanced approach fuels your body with the nutrients it needs to stay strong and healthy.',
                'type' => 'textarea',
                'group' => 'tips',
                'description' => 'Diet tip description',
                'display_order' => 4,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'tip_exercise_title',
                'value' => 'Exercise Regularly',
                'type' => 'text',
                'group' => 'tips',
                'description' => 'Exercise tip title',
                'display_order' => 5,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'tip_exercise_text',
                'value' => 'Regular physical activity is one of the best investments you can make in your health. Whether you prefer brisk walking, swimming, cycling, or yoga, aim for at least 30 minutes of movement most days. Find activities you enjoy, and you\'ll be more likely to stick with them long-term.',
                'type' => 'textarea',
                'group' => 'tips',
                'description' => 'Exercise tip description',
                'display_order' => 6,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'tip_sleep_title',
                'value' => 'Get Adequate Sleep',
                'type' => 'text',
                'group' => 'tips',
                'description' => 'Sleep tip title',
                'display_order' => 7,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'tip_sleep_text',
                'value' => 'Quality sleep is when your body repairs and rejuvenates itself. Most adults need 7-9 hours of restful sleep each night. Create a calming bedtime routine, keep your bedroom cool and dark, and try to go to bed and wake up at consistent times to support your natural sleep cycle.',
                'type' => 'textarea',
                'group' => 'tips',
                'description' => 'Sleep tip description',
                'display_order' => 8,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'tip_stress_title',
                'value' => 'Manage Stress',
                'type' => 'text',
                'group' => 'tips',
                'description' => 'Stress management tip title',
                'display_order' => 9,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'tip_stress_text',
                'value' => 'Managing stress is crucial for maintaining both physical and mental health. Explore techniques that work for you, such as meditation, deep breathing exercises, or mindfulness practices. Chronic stress can impact your immune system, so make time for activities that bring you peace and relaxation.',
                'type' => 'textarea',
                'group' => 'tips',
                'description' => 'Stress management tip description',
                'display_order' => 10,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'tip_checkups_title',
                'value' => 'Regular Health Checkups',
                'type' => 'text',
                'group' => 'tips',
                'description' => 'Checkups tip title',
                'display_order' => 11,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'tip_checkups_text',
                'value' => 'Preventive healthcare is your first line of defense. Regular checkups and recommended screenings allow for early detection of potential health issues, often when they\'re most treatable. Even if you\'re feeling well, these appointments are valuable for maintaining long-term health.',
                'type' => 'textarea',
                'group' => 'tips',
                'description' => 'Checkups tip description',
                'display_order' => 12,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'cta_title',
                'value' => 'Have Health Questions?',
                'type' => 'text',
                'group' => 'cta',
                'description' => 'CTA section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'cta_description',
                'value' => 'Our medical experts are here to provide personalized health guidance.',
                'type' => 'textarea',
                'group' => 'cta',
                'description' => 'CTA section description',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'health-tips',
                'key' => 'cta_button_text',
                'value' => 'Get Expert Advice',
                'type' => 'text',
                'group' => 'cta',
                'description' => 'CTA button text',
                'display_order' => 3,
            ],

            // DISEASE PREVENTION PAGE
            [
                'page_slug' => 'disease-prevention',
                'key' => 'hero_title',
                'value' => 'Disease Prevention',
                'type' => 'text',
                'group' => 'hero',
                'description' => 'Disease prevention page hero title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'disease-prevention',
                'key' => 'hero_subtitle',
                'value' => 'Learn about effective prevention strategies, important health screenings, and proactive measures you can take to protect yourself and your loved ones from common diseases.',
                'type' => 'textarea',
                'group' => 'hero',
                'description' => 'Disease prevention page hero subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'disease-prevention',
                'key' => 'strategies_section_title',
                'value' => 'Prevention Strategies',
                'type' => 'text',
                'group' => 'strategies',
                'description' => 'Prevention strategies section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'disease-prevention',
                'key' => 'strategies_section_subtitle',
                'value' => 'Proactive measures to protect your health and prevent diseases',
                'type' => 'text',
                'group' => 'strategies',
                'description' => 'Prevention strategies section subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'disease-prevention',
                'key' => 'cta_title',
                'value' => 'Start Your Prevention Journey',
                'type' => 'text',
                'group' => 'cta',
                'description' => 'CTA section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'disease-prevention',
                'key' => 'cta_description',
                'value' => 'Consult with our healthcare experts to create a personalized prevention plan.',
                'type' => 'textarea',
                'group' => 'cta',
                'description' => 'CTA section description',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'disease-prevention',
                'key' => 'cta_button_text',
                'value' => 'Schedule Consultation',
                'type' => 'text',
                'group' => 'cta',
                'description' => 'CTA button text',
                'display_order' => 3,
            ],

            // WELLNESS GUIDE PAGE
            [
                'page_slug' => 'wellness-guide',
                'key' => 'hero_title',
                'value' => 'Wellness Guide',
                'type' => 'text',
                'group' => 'hero',
                'description' => 'Wellness guide page hero title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'wellness-guide',
                'key' => 'hero_subtitle',
                'value' => 'Explore our holistic approach to wellness, covering physical health, mental wellbeing, nutrition, and lifestyle factors that contribute to a healthier, happier life.',
                'type' => 'textarea',
                'group' => 'hero',
                'description' => 'Wellness guide page hero subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'wellness-guide',
                'key' => 'pillars_section_title',
                'value' => 'Pillars of Wellness',
                'type' => 'text',
                'group' => 'pillars',
                'description' => 'Pillars section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'wellness-guide',
                'key' => 'pillars_section_subtitle',
                'value' => 'A holistic approach to health and well-being',
                'type' => 'text',
                'group' => 'pillars',
                'description' => 'Pillars section subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'wellness-guide',
                'key' => 'cta_title',
                'value' => 'Begin Your Wellness Journey',
                'type' => 'text',
                'group' => 'cta',
                'description' => 'CTA section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'wellness-guide',
                'key' => 'cta_description',
                'value' => 'Get personalized wellness guidance from our healthcare experts.',
                'type' => 'textarea',
                'group' => 'cta',
                'description' => 'CTA section description',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'wellness-guide',
                'key' => 'cta_button_text',
                'value' => 'Get Started',
                'type' => 'text',
                'group' => 'cta',
                'description' => 'CTA button text',
                'display_order' => 3,
            ],

            // FAQ PAGE
            [
                'page_slug' => 'faq',
                'key' => 'hero_title',
                'value' => 'Frequently Asked Questions',
                'type' => 'text',
                'group' => 'hero',
                'description' => 'FAQ page hero title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'faq',
                'key' => 'hero_subtitle',
                'value' => 'Browse answers to frequently asked questions about medical tourism in India, our services, treatment processes, and what to expect during your medical journey.',
                'type' => 'textarea',
                'group' => 'hero',
                'description' => 'FAQ page hero subtitle',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'faq',
                'key' => 'cta_title',
                'value' => 'Still Have Questions?',
                'type' => 'text',
                'group' => 'cta',
                'description' => 'CTA section title',
                'display_order' => 1,
            ],
            [
                'page_slug' => 'faq',
                'key' => 'cta_description',
                'value' => 'Our team is here to help. Contact us for personalized assistance and answers to your specific questions.',
                'type' => 'textarea',
                'group' => 'cta',
                'description' => 'CTA section description',
                'display_order' => 2,
            ],
            [
                'page_slug' => 'faq',
                'key' => 'cta_button_text',
                'value' => 'Contact Us',
                'type' => 'text',
                'group' => 'cta',
                'description' => 'CTA button text',
                'display_order' => 3,
            ],
        ];

        foreach ($contents as $content) {
            Content::updateOrCreate(
                [
                    'page_slug' => $content['page_slug'],
                    'key' => $content['key'],
                ],
                $content
            );
        }
    }
}
